### ISSUE TITLE
CSharp Colors for Visual Studio IDE?

### ISSUE THREAD

**Issue by ElektroStudios** [Logerfo/csharp-colors#23]
Hi.

Maybe is there any chance you can reproduce this extension for Visual Studio IDE?. For at least C# and VB.NET code editors?...

I ask this because currently there is not a single extension in the Visual Studio Market Place able to draw/preview the color under **Color.FromArgb()** method like your extension does for VS Code. Every existing extension for Visual Studio, except one, only works for .css files, and the other works for .css files too but also for preview web colors in C# and Vb.NET code editors and only when using **ColorTranslator.FromHtml()** method.

In the past, **Telerik** company provided a commercial product that was able to do this what I'm requesting to you, apart from other editor enhancements, however they discontinued that product when VS 2017 came out and can't be used/installed anymore.

By the way, great job this extension for VS Code.

Thanks for read.

**Comment by Logerfo** [comment]
There is already a product that does what you're asking for: [Resharper](https://www.jetbrains.com/resharper/). It's not free, though. The reason why I wrote this extension is exactly to mimic Resharper's behavior on Visual Studio Code.
Since I already have a Resharper license, I don't have plans on porting my own extension into Visual Studio IDE. On the other hand, anyone should feel free to use my code to replicate the Visual Studio Code extension into Visual Studio IDE, no credits required. I don't think it should be hard...
If someone does it, feel free to comment a link to the marketplace for your extension, so anyone looking for it should find it.
